version: '3.8'

services:
  chatwoot-postgres:
    image: postgres:15-alpine
    container_name: chatwoot-postgres
    environment:
      POSTGRES_USER: chatwoot
      POSTGRES_PASSWORD: chatwoot123
      POSTGRES_DB: chatwoot_production
    volumes:
      - chatwoot_postgres_data:/var/lib/postgresql/data
    networks:
      - lily-network

  chatwoot-redis:
    image: redis:7-alpine
    container_name: chatwoot-redis
    command: redis-server --appendonly yes
    volumes:
      - chatwoot_redis_data:/data
    networks:
      - lily-network

  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot
    depends_on:
      - chatwoot-postgres
      - chatwoot-redis
    ports:
      - "8080:3000"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE: replace-with-your-secret-key-base-64-chars-minimum
      DATABASE_URL: postgres://chatwoot:chatwoot123@chatwoot-postgres:5432/chatwoot_production
      REDIS_URL: redis://chatwoot-redis:6379
      FRONTEND_URL: http://localhost:8080
      DEFAULT_LOCALE: en
      FORCE_SSL: false
      ENABLE_ACCOUNT_SIGNUP: false
      # Mailer config (optional)
      MAILER_SENDER_EMAIL: lily-ai@example.com
      SMTP_ADDRESS: smtp.example.com
      SMTP_PORT: 587
      SMTP_DOMAIN: example.com
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_AUTHENTICATION: plain
      SMTP_ENABLE_STARTTLS_AUTO: true
    command: sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    networks:
      - lily-network

  chatwoot-worker:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot-worker
    depends_on:
      - chatwoot-postgres
      - chatwoot-redis
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: replace-with-your-secret-key-base-64-chars-minimum
      DATABASE_URL: postgres://chatwoot:chatwoot123@chatwoot-postgres:5432/chatwoot_production
      REDIS_URL: redis://chatwoot-redis:6379
      FRONTEND_URL: http://localhost:8080
    command: bundle exec sidekiq -C config/sidekiq.yml
    networks:
      - lily-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: http://localhost:5678/
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_ENCRYPTION_KEY: your-encryption-key-32-chars-min
      DB_TYPE: sqlite
      DB_SQLITE_DATABASE: /home/node/.n8n/database.sqlite
      EXECUTIONS_PROCESS: main
      GENERIC_TIMEZONE: America/New_York
    volumes:
      - n8n_data:/home/node/.n8n
      - ../n8n_workflows:/workflows
    networks:
      - lily-network

volumes:
  chatwoot_postgres_data:
  chatwoot_redis_data:
  n8n_data:

networks:
  lily-network:
    external: true