version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lily-postgres
    environment:
      POSTGRES_USER: lily
      POSTGRES_PASSWORD: lily123
      POSTGRES_DB: lily_saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lily -d lily_saas"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lily-network

  redis:
    image: redis:7-alpine
    container_name: lily-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lily-network

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: lily-api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://lily:lily123@postgres:5432/lily_saas
      REDIS_URL: redis://redis:6379
    volumes:
      - ../backend:/app
      - /app/.venv  # Exclude venv from volume mount
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - lily-network

  worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: lily-worker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://lily:lily123@postgres:5432/lily_saas
      REDIS_URL: redis://redis:6379
    volumes:
      - ../backend:/app
      - /app/.venv
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m app.workers.worker
    networks:
      - lily-network

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: lily-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - lily-network

volumes:
  postgres_data:
  redis_data:

networks:
  lily-network:
    driver: bridge